name: Release and Version Update

on:
  push:
    branches:
      - main
  # Uncomment below to trigger on tags
  # tag:
  #   - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0 || echo v0.0.0)" >> $GITHUB_OUTPUT

      - name: Bump version and update README
        run: |
          # Extract current version
          current_version=${{ steps.get_tag.outputs.tag }}
          # Bump patch version (simple example)
          IFS='.' read -r major minor patch <<< "${current_version#v}"
          new_patch=$((patch+1))
          new_version="v${major}.${minor}.${new_patch}"
          # Update README.md (add version badge or text)
          sed -i "1s/^/Version: ${new_version}\n/" newrelic_logging/README.md
          # Commit changes
          git add newrelic_logging/README.md
          git commit -m "Bump version to ${new_version} [skip ci]" || echo "No changes to commit"
          git tag ${new_version}
          git push origin main --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
